# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp
dist: xenial

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y make cmake cppcheck valgrind g++-multilib mingw-w64

script:
  # 1) Static code analysis
  - cppcheck . --error-exitcode=1 --quiet
  # 2) Run test suite (64-bit)
  - mkdir build
  - cd build
  - |
    cmake .. -DCMAKE_C_FLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2" \
             -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2"
  - make -j4 VERBOSE=1
  - ctest
  # 3) Runtime memory analysis
  - cd test
  - valgrind --error-exitcode=1 ./test1 30000
  # 4) Run test suite (32-bit)
  - cd ../..
  - rm -rf build
  - mkdir build
  - cd build
  - |
    cmake .. -DCMAKE_C_FLAGS="-m32 -g -O3 -Wall -pedantic -Wextra -Werror -Wno-unused-parameter -Wno-long-long" \
             -DCMAKE_CXX_FLAGS="-m32 -g -O3 -Wall -pedantic -Wextra -Werror -Wno-unused-parameter -Wno-long-long"
  - make -j4 VERBOSE=1
  - ctest
  # 5) Compile using MinGW
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - |
    cmake .. -DCMAKE_SYSTEM_NAME=Windows \
             -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc-posix \
             -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++-posix \
             -DCMAKE_C_FLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2" \
             -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2" \
             -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
             -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
  - make -j4 VERBOSE=1
